//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeartFluttering.Resources.Localization.RegistrForm {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InscriptionsSignUp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InscriptionsSignUp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeartFluttering.Resources.Localization.RegistrForm.InscriptionsSignUp", typeof(InscriptionsSignUp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт с таким логином уже существует.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле для города обязательно для заполнения.
        /// </summary>
        internal static string CityField {
            get {
                return ResourceManager.GetString("CityField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такого города не сущеcтвует.
        /// </summary>
        internal static string CityIsNotExists {
            get {
                return ResourceManager.GetString("CityIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация прошла успешно.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В вашем имени должны быть только буквы.
        /// </summary>
        internal static string LettersInName {
            get {
                return ResourceManager.GetString("LettersInName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В вашей фамилии должны быть только буквы.
        /// </summary>
        internal static string LettersInSurname {
            get {
                return ResourceManager.GetString("LettersInSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле для логина обязательно для заполнения.
        /// </summary>
        internal static string LoginField {
            get {
                return ResourceManager.GetString("LoginField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли должны совпадать.
        /// </summary>
        internal static string MatchingPassword {
            get {
                return ResourceManager.GetString("MatchingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле для имени обязательно для заполнения.
        /// </summary>
        internal static string NameField {
            get {
                return ResourceManager.GetString("NameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вам не может быть столько много лет.
        /// </summary>
        internal static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт с таким паролем уже существует.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле для пароля обязательно для заполнения.
        /// </summary>
        internal static string PasswordField {
            get {
                return ResourceManager.GetString("PasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле для повторного пароля обязательно для заполнения.
        /// </summary>
        internal static string RepeatPasswordField {
            get {
                return ResourceManager.GetString("RepeatPasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле для пола обязательно для заполнения.
        /// </summary>
        internal static string SexField {
            get {
                return ResourceManager.GetString("SexField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле для фамилии обязательно для заполнения.
        /// </summary>
        internal static string SurnameFiald {
            get {
                return ResourceManager.GetString("SurnameFiald", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ещё слишком молоды.
        /// </summary>
        internal static string Youth {
            get {
                return ResourceManager.GetString("Youth", resourceCulture);
            }
        }
    }
}
